# Evaluate Coefficients of Logistic Regression

[Machine Learning Interpretability course](https://www.trainindata.com/p/machine-learning-interpretability)

In this notebook, we will evaluate the coefficients of the logistic regression. We will first use `statsmodels` and then `sklearn`.

`statsmodels` returns the statistics and p-values out of the box, utilizing MLE. For `sklearn`, we will obtain these parameters manually, also using the derivations from MLE.

If the coefficients are significant, then the contribution of the feature towards the probability is meaningful.

In [1]:
import numpy as np
import pandas as pd
from scipy import stats

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import statsmodels.api as sm

### Load data

To obtain the data, check the folder `prepare-data` in this repo or section 2 in the course.

In [2]:
# load titanic dataset

df = pd.read_csv('../titanic.csv')

# split data
X_train, X_test, y_train, y_test = train_test_split(
    df.drop("survived", axis=1), 
    df["survived"],
    test_size=0.15,
    random_state=1,
)

# scale the variables
scaler = StandardScaler().set_output(transform="pandas")

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## Statsmodels

In [3]:
# Our model needs an intercept so we add a column of 1s:

X_train_sm = sm.add_constant(X_train)
X_test_sm = sm.add_constant(X_test)

In [4]:
# Fit logistic regression model

logit_mod = sm.Logit(y_train, X_train_sm)

logit_res = logit_mod.fit()

print(logit_res.summary())

Optimization terminated successfully.
         Current function value: 0.469479
         Iterations 6
                           Logit Regression Results                           
Dep. Variable:               survived   No. Observations:                 1112
Model:                          Logit   Df Residuals:                     1098
Method:                           MLE   Df Model:                           13
Date:                Wed, 02 Sep 2026   Pseudo R-squ.:                  0.2923
Time:                        16:56:21   Log-Likelihood:                -522.06
converged:                       True   LL-Null:                       -737.67
Covariance Type:            nonrobust   LLR p-value:                 5.606e-84
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.6505      0.079     -8.267      0.000      -0.805      -0.496
pclass        -0.5174      0.

With statsmodels, the statistical testing of the coefficients comes out of the box.

We see that some coefficients are not statistically significant, so we could remove those features from the model.

## Scikit-learn

In [5]:
# fit model

logit = LogisticRegression(l1_ratio=0, random_state=1)

logit.fit(X_train, y_train)

,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",1
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver b

### Empirically

We follow the derivations shown [here](https://web.stanford.edu/class/archive/stats/stats200/stats200.1172/Lecture26.pdf) and the Python implementation shown [here](https://stats.stackexchange.com/questions/89484/how-to-compute-the-standard-errors-of-a-logistic-regressions-coefficients).

In [6]:
# the target classes

logit.classes_

array([0, 1])

In [7]:
# matrix of predicted class probabilities

pred_train = logit.predict_proba(X_train)

pred_train

array([[0.89498864, 0.10501136],
       [0.76116749, 0.23883251],
       [0.55551715, 0.44448285],
       ...,
       [0.93766697, 0.06233303],
       [0.71612957, 0.28387043],
       [0.41455349, 0.58544651]], shape=(1112, 2))

In [8]:
# add column of 1's at the beginning of X_train

X_train_c = np.hstack([np.ones((X_train.shape[0], 1)), X_train])

X_train_c

array([[ 1.        ,  0.83427143, -0.47413915, ..., -0.12827074,
         0.5399273 , -0.06720649],
       [ 1.        , -0.36742524,  0.46905   , ..., -0.12827074,
         0.5399273 , -0.06720649],
       [ 1.        ,  0.83427143,  2.35542828, ..., -0.12827074,
         0.5399273 , -0.06720649],
       ...,
       [ 1.        ,  0.83427143,  2.35542828, ..., -0.12827074,
         0.5399273 , -0.06720649],
       [ 1.        , -1.56912191, -0.47413915, ..., -0.12827074,
         0.5399273 , -0.06720649],
       [ 1.        ,  0.83427143, -0.47413915, ..., -0.12827074,
         0.5399273 , -0.06720649]], shape=(1112, 14))

In [9]:
# Create matrix of 0's, where diagonal contains each 
# predicted observation's variance.

W = np.diagflat(np.prod(pred_train, axis=1))

W

array([[0.09398397, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.18179154, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.24691785, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.05844763, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.20328801,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.24269889]], shape=(1112, 1112))

In [10]:
# The variance is the product of the probabilities

# For the first observation:
0.89651014 * 0.10348986

0.0927797088771804

In [11]:
# Covariance matrix, it is derived empirically.

# (XT W X)−1

cov_m = np.linalg.inv(np.dot(np.dot(X_train_c.T, W), X_train_c))

cov_m

array([[ 6.15335707e-03,  9.28363041e-04,  3.97111625e-04,
        -1.29111035e-04, -9.55399846e-04,  3.26530918e-04,
         1.26054822e-04,  7.02773169e-04,  6.82556039e-04,
         5.51369861e-04,  4.19786241e-04,  1.65356630e-04,
         8.23601161e-04,  2.62517413e-05],
       [ 9.28363041e-04,  1.38271029e-02, -7.86203471e-04,
        -5.80194454e-04, -5.22589166e-04,  3.36545687e-03,
         3.12154556e-03,  5.09759780e-03,  6.25328802e-03,
         3.36860686e-03,  3.82762558e-03,  2.91098572e-03,
        -4.78152410e-04, -2.57322539e-04],
       [ 3.97111625e-04, -7.86203471e-04,  8.98009842e-03,
        -2.27727709e-03, -1.15587387e-03, -1.24687564e-03,
        -7.56075476e-04, -3.49184987e-04, -9.16652105e-04,
        -1.35739166e-04, -2.30038963e-04, -5.82238585e-05,
        -1.29845598e-04,  2.41034677e-04],
       [-1.29111035e-04, -5.80194454e-04, -2.27727709e-03,
         6.68788983e-03, -1.25672115e-03, -1.41224765e-03,
        -1.31688231e-03, -1.29259328e-04,  3.

In [12]:
# Standard errors

se = np.sqrt(np.diag(cov_m))

se

array([0.07844334, 0.1175887 , 0.09476338, 0.08177952, 0.08169996,
       0.12515724, 0.12709883, 0.14840847, 0.1700556 , 0.12922639,
       0.13026778, 0.09950081, 0.23624343, 0.07330029])

In [13]:
# capture name of features

features = np.insert(logit.feature_names_in_, 0, "intercept")

features

array(['intercept', 'pclass', 'sibsp', 'parch', 'sex_female',
       'embarked_S', 'embarked_C', 'cabin_B', 'cabin_C', 'cabin_E',
       'cabin_D', 'cabin_A', 'cabin_M', 'cabin_G'], dtype=object)

In [14]:
# capture coefficients of the logit including the intercept

coefficients = np.insert(logit.coef_[0], 0, logit.intercept_[0])

coefficients

array([-0.6479166 , -0.50653352, -0.22433459,  0.05542229,  1.18930029,
       -0.01137079,  0.22903986, -0.18471814, -0.33346052,  0.00140516,
       -0.16837707, -0.08527607, -0.62155447, -0.1332394 ])

In [15]:
# Wald's statistic (coefficient / s.e.)

z_scores = (coefficients / np.sqrt(np.diag(cov_m)))

z_scores

array([-8.25967666e+00, -4.30767165e+00, -2.36731306e+00,  6.77703757e-01,
        1.45569265e+01, -9.08520183e-02,  1.80206120e+00, -1.24466036e+00,
       -1.96089112e+00,  1.08736322e-02, -1.29254575e+00, -8.57038941e-01,
       -2.63099153e+00, -1.81771989e+00])

In [16]:
# p-values

p_values = stats.norm.sf(abs(z_scores))*2  # two sided

p_values

array([1.46067606e-16, 1.64982057e-05, 1.79177692e-02, 4.97959544e-01,
       5.27779109e-48, 9.27610176e-01, 7.15357777e-02, 2.13256622e-01,
       4.98917260e-02, 9.91324268e-01, 1.96168212e-01, 3.91423364e-01,
       8.51361568e-03, 6.91069567e-02])

In [17]:
# put everything together

coeffs = pd.DataFrame({
    "feature": features,
    "coeff": coefficients,
    "std": se,
    "z": z_scores,
    "p_value": p_values,
})

coeffs

,feature,coeff,std,z,p_value
0,intercept,-0.647917,0.078443,-8.259677,1.460676e-16
1,pclass,-0.506534,0.117589,-4.307672,1.649821e-05
2,sibsp,-0.224335,0.094763,-2.367313,1.791777e-02
3,parch,0.055422,0.081780,0.677704,4.979595e-01
4,sex_female,1.189300,0.081700,14.556926,5.277791e-48
5,embarked_S,-0.011371,0.125157,-0.090852,9.276102e-01
6,embarked_C,0.229040,0.127099,1.802061,7.153578e-02
7,cabin_B,-0.184718,0.148408,-1.244660,2.132566e-01
8,cabin_C,-0.333461,0.170056,-1.960891,4.989173e-02
9,cabin_E,0.001405,0.129226,0.010874,9.913243e-01


In [18]:
# Compare with statsmodels

print(logit_res.summary())

                           Logit Regression Results                           
Dep. Variable:               survived   No. Observations:                 1112
Model:                          Logit   Df Residuals:                     1098
Method:                           MLE   Df Model:                           13
Date:                Wed, 02 Sep 2026   Pseudo R-squ.:                  0.2923
Time:                        16:56:21   Log-Likelihood:                -522.06
converged:                       True   LL-Null:                       -737.67
Covariance Type:            nonrobust   LLR p-value:                 5.606e-84
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.6505      0.079     -8.267      0.000      -0.805      -0.496
pclass        -0.5174      0.118     -4.389      0.000      -0.748      -0.286
sibsp         -0.2268      0.095     -2.383      0.0

We got the same values. Nicely done. Now you know how the values are calculated under the hood in `statsmodels`, and how to determine them if you are using `sklearn`.